#!/usr/bin/bash
# vim: ft=bash

set -euo pipefail

TMPDIR="$(mktemp -d)"
# Updated on 2023-01-13
URL="https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.27.2.13801.tar.gz"
FNAME=$(awk -F / '{print $NF}' <(echo "$URL"))

pushd "$TMPDIR" >/dev/null || exit
curl -LO "$URL" && tar -xf "$FNAME"

mkdir -p "$HOME"/.local/bin/
cp "${FNAME%%.tar.gz}"/jetbrains-toolbox "$HOME"/.local/bin

[ -t 0 ] || nohup "$HOME"/.local/bin/jetbrains-toolbox &
