#!/usr/bin/env bash

set -euo pipefail

DIR=$(mktemp -d)
# Updated on 2023-01-13
URL="https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.27.2.13801.tar.gz"
FNAME=$(awk -F / '{print $NF}' <(echo "$URL"))

cd "$DIR" || exit
curl -LO "$URL"
tar -xzf "$FNAME"

mkdir -p "$HOME"/.local/bin/
cp "${FNAME%%.tar.gz}"/jetbrains-toolbox "$HOME"/.local/bin

[ -t 0 ] || nohup "$HOME"/.local/bin/jetbrains-toolbox &
